---
text_splitter:
  chunk_size: 100
  chunk_overlap: 50
embeddings:
  model_path: "../assets/"
  n_ctx: 2048
  n_gpu_layers: 1
  n_threads: 8
  n_batch: 512
llm:
  model_path: "../assets/llama-2-13b.Q4_0.gguf"
  n_gpu_layers: 1
  n_batch: 512
  n_ctx: 2048
rag_prompt:
  template: >
    [INST]<<SYS>> Answer all questions yes or no ONLY no other text at all.
    <</SYS>> \nQuestion: {question} \nContext: {context} \nAnswer: [/INST]