---
text_splitter:
  chunk_size: 100
  chunk_overlap: 50
embeddings:  # TODO: use this instead of downloading weights at launch time
  model_path: "../assets/"
  n_ctx: 2048
  n_gpu_layers: 1
  n_threads: 8
  n_batch: 512
llm:
  model_path: "../assets/llama-2-70b-chat.Q4_K_M.gguf"
  n_gpu_layers: 1
  n_batch: 512
  n_ctx: 2048
rag_prompt:
  template: >
    [INST]<<SYS>> Answer the questions in one sentece or less. Stick very closely
    to the information in the context. Be direct, short, and clear.
    <</SYS>> \nQuestion: {question} \nContext: {context} \nAnswer: [/INST]