# Desgined for use in ray 2.10 and up
proxy_location: HeadOnly

http_options:
  host: 0.0.0.0
  port: 8000

applications:
- name: rag
  route_prefix: /rag
  import_path: launch:response
  runtime_env: {}

  deployments:
  - name: Rag
    num_replicas: 1
    max_concurrent_queries: 1
    ray_actor_options:
      num_cpus: 1.0
      num_gpus: 0.0
