# Desgined for use in ray 2.10 and up
proxy_location: HeadOnly

http_options:
  host: 0.0.0.0
  port: 8001

applications:
- name: example-service
  route_prefix: /example-service
  import_path: launch:response
  runtime_env: {}

  deployments:
  - name: ExampleService
    num_replicas: 1
    max_concurrent_queries: 1
    ray_actor_options:
      num_cpus: 1.0
      num_gpus: 0.0

  deployments:
  - name: Rag
    num_replicas: 1
    max_concurrent_queries: 1
    ray_actor_options:
      num_cpus: 1.0
      num_gpus: 0.0

  deployments:
  - name: ChromaClient
    num_replicas: 1
    max_concurrent_queries: 1
    ray_actor_options:
      num_cpus: 1.0
      num_gpus: 0.0
